name: terraform apply
on:
  workflow_call:
    inputs:
      update-image:
        type: boolean
        default: true
        description: "Whether to update container image or not"
  workflow_dispatch:
    inputs:
      update-image:
        type: boolean
        default: true
        description: "Whether to update container image or not"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/main/
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
      - uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_APPLY_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Init terraform
        run: terraform init
      - name: Get image tag
        id: image-tag
        run:
          if [ "${{inputs.update-image}}" = "true" ]; then
            echo "image-tag=${{github.sha}}" >> "$GITHUB_OUTPUT"
          else
            echo "image-tag=$(terraform output latest_image_tag)" >> "$GITHUB_OUTPUT"
          fi
      - name: Apply terraform
        run: |
          terraform apply -auto-approve -input=false -var="commit_sha256=${{steps.image-tag.outputs.image-tag}}"\
            -var="github-app-id=${{vars.GH_APP_ID}}"\
            -var="github-installation-id=${{vars.GH_INSTALLATION_ID}}"\
            -var="discord-app-id=${{vars.DISCORD_APP_ID}}"\
            -var="discord-public-key=${{vars.DISCORD_PUBLIC_KEY}}"
        env:
          ARM_USE_OIDC: true
