name: CD
on:
  push:
    branches: master

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  deploy-image:
    needs: ci
    if: ${{ needs.ci.outputs.discord-bot-success }}
    uses: ./.github/workflows/deploy_image.yaml
    with:
      version: v0.0.0 #TODO: dummy

  apply-terraform:
    needs: ci
    if: ${{ needs.ci.outputs.terraform-success }}
    uses: ./.github/workflows/apply_terraform.yaml
    with:
      update-image: ${{ needs.ci.outputs.update-image }}
  
  update-page:
    needs: ci
    if: ${{ needs.ci.outputs.page-updater-success }}
    uses: ./.github/workflows/update_page.yaml
