name: CD
on:
  push:
    branches: master

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout:
          fetch-depth: '0'
      - name: Get version
        id: get-version
        run: |
          TAG=$(git describe --tags --abbrev=0 --match "discord-bot/**")
          echo "version=${TAG#discord-bot/}" >> "$GITHUB_OUTPUT"

  deploy-discord-bot:
    needs: [ci,get-version]
    if: ${{ needs.ci.outputs.discord-bot-success == 'true' }}
    uses: ./.github/workflows/deploy_discord_bot.yaml
    with:
      version: ${{ needs.get-version.outputs.version }}

  deploy-deletion-detector:
    needs: ci
    if: ${{ needs.ci.outputs.deletion-detector-success == 'true' }}
    uses: ./.github/workflows/deploy_deletion_detector.yaml

  apply-terraform:
    needs: [ci, deploy-discord-bot, deploy-deletion-detector]
    if: ${{ needs.ci.outputs.terraform-success == 'true' || needs.ci.outputs.discord-bot-success == 'true' || needs.ci.outputs.deletion-detector-success == 'true' }}
    uses: ./.github/workflows/apply_terraform.yaml
    with:
      update-discord-bot: ${{ needs.ci.outputs.discord-bot-success == 'true' }}
      update-deletion-detector: ${{ needs.ci.outputs.deletion-detector-success == 'true' }}
  
  update-page:
    needs: ci
    if: ${{ needs.ci.outputs.page-updater-success == 'true' }}
    uses: ./.github/workflows/update_page.yaml
    secrets:
      WIKIWIKI_PASSWORD: ${{ secrets.WIKIWIKI_PASSWORD }}
