name: CI
on:
  pull_request:
    branches: master
  workflow_call:
    outputs:
      page-updater-success:
        value: ${{ jobs.page-updater-check.result == 'success' }}
      discord-bot-success:
        value: ${{ jobs.discord-bot-check.result == 'success' }}
      terraform-success:
        value: ${{ jobs.terraform-check.result == 'success' }}
      update-image:
        description: "whether container image should be updated or not"
        value: ${{ jobs.paths-filter.outputs.terraform-image-only == 'true' || jobs.paths-filter.outputs.terraform-both == 'true' }}

jobs:
  paths-filter:
    uses: ./.github/workflows/paths_filter.yaml

  page-updater-check:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.page-updater == 'true' }}
    defaults:
      run:
        working-directory: page-updater/
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            types/
            wikiwiki/
            page-updater/
      - uses: actions/setup-go@v7
        with:
          go-version-file: ./page-updater/go.mod
          cache-dependency-path: ./page-updater/go.sum
      - name: Run tests
        run: go test
  
  discord-bot-check:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.discord-bot == 'true' }}
    defaults:
      run:
        working-directory: discord-bot/
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            discord-bot/
            types/
      - uses: actions/setup-go@v7
        with:
            go-version-file: ./discord-bot/go.mod
            cache-dependency-path: ./discord-bot/go.sum
      - name: Run tests
        run: go test
  
  terraform-check:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.terraform-both == 'true' || needs.paths-filter.outputs.terraform-image-only == 'true' || needs.paths-filter.outputs.terraform-infra-only == 'true' }}
    steps:
      - name: debug
        run: |
          echo "terraform-both = ${{needs.paths-filter.outputs.terraform-both}}"
          echo "terraform-image-only = ${{needs.paths-filter.outputs.terraform-image-only}}"
          echo "terraform-infra-only = ${{needs.paths-filter.outputs.terraform-infra-only}}"
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            terraform/
      - uses: hashicorp/setup-terraform@v4
      - name: Init and validate .tf files for bootstrap
        run: |
          cd terraform/bootstrap/
          terraform init -backend=false
          terraform validate
      - name: Init and validate .tf files for main
        run: |
          cd terraform/main/
          terraform init -backend=false
          terraform validate
  