name: CI
on:
  pull_request:
    branches: master
  workflow_call:
    outputs:
      page_updater_success:
        value: ${{ jobs.page_updater_check.result == 'success' }}
      discord_bot_success:
        value: ${{ jobs.discord_bot_check.result == 'success' }}
      terraform_success:
        value: ${{ jobs.terraform_check.result == 'success' }}
      update_image:
        description: "whether container image should be updated or not"
        value: ${{ jobs.paths_filter.outputs.terraform_image_only || jobs.paths_filter.outputs.terraform_both }}

jobs:
  paths_filter:
    uses: ./.github/workflows/paths_filter.yaml

  page_updater_check:
    runs-on: ubuntu-latest
    needs: paths_filter
    if: ${{ needs.paths_filter.outputs.page_updater }}
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            go.work
            go.sum
            common/
            page-updater/
      - uses: actions/setup-go@v7
        with:
          go-version-file: ./go.work
      - name: Run tests
        run: go test ./page-updater
  
  discord_bot_check:
    runs-on: ubuntu-latest
    needs: paths_filter
    if: ${{ needs.paths_filter.outputs.discord_bot }}
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            go.work
            go.sum
            discord_bot/
            common/
      - uses: actions/setup-go@v7
        with:
            go-version-file: ./go.work
      - name: Run tests
        run: go test ./discord-bot
  
  terraform_check:
    runs-on: ubuntu-latest
    needs: paths_filter
    if: ${{ needs.paths_filter.outputs.terraform_both || needs.paths_filter.outputs.terraform_image_only || needs.paths_filter.outputs.terraform_infra_only }}
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            terraform/
      - uses: hashicorp/setup-terraform@v4
      - name: Validate .tf files for bootstrap
        run: |
          cd terraform/bootstrap/
          terraform validate
      - name: Validate .tf files for main
        run: |
          cd terraform/main/
          terraform validate
          
  