name: Deploy Deletion Detector
on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          sparse-checkout: |
            deletion-detector/
            wikiwiki/
      - uses: azure/login@487024fc392f1f60cc70bc8a48233c14bc1de77f
        with:
          client-id: ${{ vars.AZURE_DEPLOY_BOT_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Login to ACR
        run: az acr login --name kokkimusumeDiscordbotRegistry
      - name: Build and push
        run: |
          TAG=kokkimusumediscordbotregistry.azurecr.io/deletion-detector:${{github.sha}}
          docker build -t $TAG -f ./deletion-detector/Dockerfile .
          docker push $TAG
