name: Workflow
on:
  push:
  workflow_dispatch:

jobs:
  generate_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: ./go.mod
      - run: go run .
        env:
          WIKIWIKI_PASSWORD: ${{ secrets.WIKIWIKI_PASSWORD }}
    
