name: Paths Filter
on:
  workflow_call:
    outputs:
      page-updater: 
        value: ${{ jobs.paths-filter.outputs.page-updater }}
      discord-bot:
        value: ${{ jobs.paths-filter.outputs.discord-bot }}
      deletion-detector:
        value: ${{ jobs.paths-filter.outputs.deletion-detector }}
      terraform:
        value: ${{ jobs.paths-filter.outputs.terraform }}
jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      page-updater: ${{ steps.filter.outputs.page-updater == 'true' }}
      discord-bot: ${{ steps.filter.outputs.discord-bot == 'true' }}
      deletion-detector: ${{ steps.filter.outputs.deletion-detector == 'true' }}
      terraform: ${{ steps.filter.outputs.terraform == 'true' }}  
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d
        id: filter
        with:
          filters: |
            page-updater:
              - 'page-updater/**'
              - 'types/**'
              - 'wikiwiki/**'
            discord-bot:
              - 'discord-bot/**'
              - 'types/**'
            terraform:
              - 'terraform/**'
            deletion-detector:
              - 'deletion-detector/**'
              - 'wikiwiki/**'
