name: Register commands
on:
  push:
    branches: main
    paths: ./discord-bot/*
  workflow_dispatch: 

jobs:
  register_commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: ./go.work
      - run:
          go run ./discord-bot/register/
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
