name: Update Pages
on:
  push:
    branches: master
    paths:
      - ./data/**
  workflow_dispatch:
  workflow_call:

jobs:
  generate_page:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: page-updater/
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            common/
            page-updater/
            data/
      - uses: actions/setup-go@v7
        with:
          go-version-file: ./page-updater/go.mod
      - run: go run .
        env:
          WIKIWIKI_PASSWORD: ${{ secrets.WIKIWIKI_PASSWORD }}
    
